use_frameworks!

platform :ios, '9.0'

target 'MYYLaunchVC_Example' do
  pod 'MYYLaunchVC', :path => '../'

  target 'MYYLaunchVC_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
